#!/bin/bash
# Agent First-Time Initialization Script
#
# This script handles the order of operations for setting up a new agent environment.
# It manages dependencies and race conditions between services.
#
# Features:
# - Auto-detects agent name from directory (artifact-review-{name} → {name})
# - Auto-generates .env.docker.local from orchestrator config.json
# - No manual configuration required
#
# Usage:
#   ./scripts/agent-init.sh              # Full first-time setup (includes secret sync)
#   ./scripts/agent-init.sh --check      # Check current state + credential sync status
#   ./scripts/agent-init.sh --env-only   # Only generate env files (no services)
#   ./scripts/agent-init.sh --sync-secrets # Sync shared secrets from parent env (non-disruptive)

set -e

# Export NODE_EXTRA_CA_CERTS for mkcert TLS support
export NODE_EXTRA_CA_CERTS="$(mkcert -CAROOT)/rootCA.pem"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
APP_DIR="$PROJECT_ROOT/app"
ORCHESTRATOR_DIR="$(dirname "$PROJECT_ROOT")/artifact-review-orchestrator"
ORCHESTRATOR_CONFIG="$ORCHESTRATOR_DIR/config.json"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log_info() { echo -e "${BLUE}ℹ${NC}  $1"; }
log_success() { echo -e "${GREEN}✅${NC} $1"; }
log_warn() { echo -e "${YELLOW}⚠️${NC}  $1"; }
log_error() { echo -e "${RED}❌${NC} $1"; }
log_step() { echo -e "\n${BLUE}━━━ $1 ━━━${NC}"; }

# =============================================================================
# Detect agent name from directory
# =============================================================================
detect_agent_name() {
    local dir_name=$(basename "$PROJECT_ROOT")

    # Extract agent name from artifact-review-{name} pattern
    if [[ "$dir_name" =~ ^artifact-review-(.+)$ ]]; then
        echo "${BASH_REMATCH[1]}"
    else
        echo ""
    fi
}

# =============================================================================
# Read config from orchestrator config.json
# =============================================================================
get_agent_config() {
    local agent_name="$1"
    local field="$2"

    if [ ! -f "$ORCHESTRATOR_CONFIG" ]; then
        echo ""
        return
    fi

    # Try agent-specific config first, fall back to default
    local value=$(jq -r ".\"$agent_name\".\"$field\" // .default.\"$field\" // empty" "$ORCHESTRATOR_CONFIG" 2>/dev/null)
    echo "$value"
}

# =============================================================================
# Generate .env.docker.local from orchestrator config
# =============================================================================
generate_env_docker_local() {
    local agent_name="$1"
    local env_file="$PROJECT_ROOT/.env.docker.local"

    # Get config from orchestrator
    local app_port=$(get_agent_config "$agent_name" "appPort")
    local subnet=$(get_agent_config "$agent_name" "subnet")

    if [ -z "$app_port" ]; then
        log_error "Could not read appPort from $ORCHESTRATOR_CONFIG for agent '$agent_name'"
        log_info "Make sure the agent is registered in config.json"
        return 1
    fi

    if [ -z "$subnet" ]; then
        log_error "Could not read subnet from $ORCHESTRATOR_CONFIG for agent '$agent_name'"
        log_info "Make sure subnet is configured in config.json"
        return 1
    fi

    log_info "Generating .env.docker.local for agent: $agent_name"
    log_info "  appPort: $app_port, subnet: $subnet"

    cat > "$env_file" << EOF
# AUTO-GENERATED by ./scripts/agent-init.sh - Do not edit directly.
# Re-run ./scripts/agent-init.sh to regenerate from orchestrator config.json
# Generated: $(date -Iseconds)

# =============================================================================
# AGENT IDENTITY
# =============================================================================
AGENT_NAME=$agent_name

# Base port - all other ports are derived from this
BASE_PORT=$app_port

# =============================================================================
# DERIVED PORTS (auto-calculated from BASE_PORT)
# =============================================================================
# These MUST be exported for docker-compose.yml to use them
CONVEX_ADMIN_PORT=$((app_port + 210))
CONVEX_HTTP_PORT=$((app_port + 211))
CONVEX_DASHBOARD_PORT=$((app_port + 3791))
MAILPIT_WEB_PORT=$((app_port + 5025))
MAILPIT_SMTP_PORT=$((app_port + 1025))

# =============================================================================
# SERVICE DOMAINS (orchestrator proxy routing)
# =============================================================================
SITE_URL=https://\${AGENT_NAME}.loc
CONVEX_CLOUD_URL=https://\${AGENT_NAME}.convex.cloud.loc
CONVEX_SITE_URL=https://\${AGENT_NAME}.convex.site.loc
MAILPIT_URL=https://\${AGENT_NAME}.mailpit.loc

# Shared services (same for all agents)
NOVU_API_URL=https://api.novu.loc
NOVU_WS_URL=wss://ws.novu.loc
NOVU_CONSOLE_URL=https://novu.loc

# =============================================================================
# DOCKER COMPOSE
# =============================================================================
INSTANCE_NAME=artifact-review-local
# NOTE: Do NOT set INSTANCE_SECRET - container generates on first start

# =============================================================================
# TLS CERTIFICATES (for resend-proxy)
# =============================================================================
MKCERT_CERTS_PATH=../artifact-review-orchestrator/certs

# =============================================================================
# RESEND PROXY NETWORK (agent-specific to avoid conflicts)
# =============================================================================
RESEND_NETWORK_SUBNET=${subnet}.0.0/16
RESEND_PROXY_IP=${subnet}.0.10
EOF

    log_success "Generated .env.docker.local"
}

# =============================================================================
# STEP 0: Check prerequisites
# =============================================================================
check_prerequisites() {
    log_step "Checking Prerequisites"

    local missing=0

    # Check node
    if command -v node &> /dev/null; then
        log_success "Node.js: $(node --version)"
    else
        log_error "Node.js not found"
        missing=1
    fi

    # Check npm
    if command -v npm &> /dev/null; then
        log_success "npm: $(npm --version)"
    else
        log_error "npm not found"
        missing=1
    fi

    # Check docker
    if command -v docker &> /dev/null; then
        if docker info &> /dev/null; then
            log_success "Docker: running"
        else
            log_error "Docker not running - start Docker first"
            missing=1
        fi
    else
        log_error "Docker not found"
        missing=1
    fi

    # Check tmux
    if command -v tmux &> /dev/null; then
        log_success "tmux: $(tmux -V)"
    else
        log_error "tmux not found"
        missing=1
    fi

    # Check jq (for reading orchestrator config.json)
    if command -v jq &> /dev/null; then
        log_success "jq: $(jq --version)"
    else
        log_error "jq not found (install with: sudo apt install jq)"
        missing=1
    fi

    if [ $missing -eq 1 ]; then
        log_error "Missing prerequisites. Please install them first."
        exit 1
    fi
}

# =============================================================================
# STEP 1: Environment Files
# =============================================================================
setup_env_files() {
    log_step "Step 1: Environment Files"

    # Check for jq (required for reading config.json)
    if ! command -v jq &> /dev/null; then
        log_error "jq is required but not installed. Install with: sudo apt install jq"
        exit 1
    fi

    # Check orchestrator config exists
    if [ ! -f "$ORCHESTRATOR_CONFIG" ]; then
        log_error "Orchestrator config not found at $ORCHESTRATOR_CONFIG"
        log_info "Make sure artifact-review-orchestrator is set up first"
        exit 1
    fi

    # Auto-detect agent name from directory
    AGENT_NAME=$(detect_agent_name)

    if [ -z "$AGENT_NAME" ]; then
        log_error "Could not detect agent name from directory"
        log_info "Directory should be named: artifact-review-{agent-name}"
        log_info "Current directory: $(basename "$PROJECT_ROOT")"
        exit 1
    fi

    log_success "Detected agent name: $AGENT_NAME"

    # Generate .env.docker.local (always regenerate to pick up config changes)
    if [ -f "$PROJECT_ROOT/.env.docker.local" ]; then
        log_info "Regenerating .env.docker.local..."
    fi
    generate_env_docker_local "$AGENT_NAME"

    # Load the generated config
    source "$PROJECT_ROOT/.env.docker.local"

    # Copy other env files if they don't exist
    cd "$PROJECT_ROOT"

    # Setup direnv if .envrc.example exists
    if [ ! -f ".envrc" ] && [ -f ".envrc.example" ]; then
        cp .envrc.example .envrc
        direnv allow . 2>/dev/null || true
        log_success "Created .envrc (direnv)"
    elif [ -f ".envrc" ]; then
        direnv allow . 2>/dev/null || true
        log_success ".envrc exists"
    fi

    if [ ! -f ".env.dev.local" ] && [ -f ".env.dev.local.example" ]; then
        cp .env.dev.local.example .env.dev.local
        log_success "Created .env.dev.local (add your dev API keys later)"
    elif [ -f ".env.dev.local" ]; then
        log_success ".env.dev.local exists"
    fi

    cd "$APP_DIR"

    if [ ! -f ".env.nextjs.local" ] && [ -f ".env.nextjs.local.example" ]; then
        # Substitute AGENT_NAME in the example
        sed "s/\${AGENT_NAME}/$AGENT_NAME/g" .env.nextjs.local.example > .env.nextjs.local
        log_success "Created app/.env.nextjs.local (secrets will be populated by setup scripts)"
    elif [ -f ".env.nextjs.local" ]; then
        log_success "app/.env.nextjs.local exists"
    fi

    if [ ! -f ".env.convex.local" ] && [ -f ".env.convex.local.example" ]; then
        # Substitute AGENT_NAME in the example (replaces james.loc placeholder)
        sed "s/james\.loc/${AGENT_NAME}.loc/g" .env.convex.local.example > .env.convex.local
        log_success "Created app/.env.convex.local (will be populated by setup scripts)"
    elif [ -f ".env.convex.local" ]; then
        log_success "app/.env.convex.local exists"
    fi

    cd "$PROJECT_ROOT"

    # Sync shared secrets from parent env file (runs regardless of file existence)
    # This ensures new shared secrets are always propagated
    sync_shared_secrets
}

# =============================================================================
# Sync shared secrets from parent .env.dev.local to agent env files
# =============================================================================
# This is idempotent - safe to run multiple times. It upserts values without
# destroying custom agent-specific configuration.
#
# Shared Parent Var             → Target File                        → Notes
# ─────────────────────────────────────────────────────────────────────────────
# STRIPE_SECRET_KEY             → app/.env.convex.local              → Convex backend
# STRIPE_WEBHOOK_SECRET         → app/.env.convex.local              → Convex backend
# STRIPE_PRICE_ID_PRO           → app/.env.convex.local              → Convex backend
# STRIPE_PRICE_ID_PRO_ANNUAL    → app/.env.convex.local              → Convex backend
# RESEND_API_KEY                → app/.env.convex.local              → Convex backend
# NOVU_SECRET_KEY               → app/.env.nextjs.local              → Next.js runtime
# NOVU_APPLICATION_IDENTIFIER   → app/.env.nextjs.local              → As NEXT_PUBLIC_NOVU_APPLICATION_IDENTIFIER
# =============================================================================
sync_shared_secrets() {
    local shared_env_file="$PROJECT_ROOT/../.env.dev.local"
    local convex_env_file="$APP_DIR/.env.convex.local"
    local nextjs_env_file="$APP_DIR/.env.nextjs.local"

    if [ ! -f "$shared_env_file" ]; then
        log_warn "Shared .env.dev.local not found at $shared_env_file"
        log_info "Secrets will need to be added manually"
        return 0
    fi

    log_info "Syncing shared secrets from ../../.env.dev.local..."

    # Read all shared vars
    local stripe_secret_key=$(grep "^STRIPE_SECRET_KEY=" "$shared_env_file" | cut -d= -f2-)
    local stripe_webhook_secret=$(grep "^STRIPE_WEBHOOK_SECRET=" "$shared_env_file" | cut -d= -f2-)
    local stripe_price_pro=$(grep "^STRIPE_PRICE_ID_PRO=" "$shared_env_file" | cut -d= -f2-)
    local stripe_price_annual=$(grep "^STRIPE_PRICE_ID_PRO_ANNUAL=" "$shared_env_file" | cut -d= -f2-)
    local resend_api_key=$(grep "^RESEND_API_KEY=" "$shared_env_file" | cut -d= -f2-)
    # NOTE: Novu credentials are PER-AGENT (from setup-novu-org.sh), NOT from shared secrets

    local synced_count=0

    # --- Sync to app/.env.convex.local ---
    if [ -f "$convex_env_file" ]; then
        # Stripe vars
        if [ -n "$stripe_secret_key" ]; then
            if upsert_env_var "$convex_env_file" "STRIPE_SECRET_KEY" "$stripe_secret_key"; then
                synced_count=$((synced_count + 1))
            fi
        fi
        if [ -n "$stripe_webhook_secret" ]; then
            if upsert_env_var "$convex_env_file" "STRIPE_WEBHOOK_SECRET" "$stripe_webhook_secret"; then
                synced_count=$((synced_count + 1))
            fi
        fi
        if [ -n "$stripe_price_pro" ]; then
            if upsert_env_var "$convex_env_file" "STRIPE_PRICE_ID_PRO" "$stripe_price_pro"; then
                synced_count=$((synced_count + 1))
            fi
        fi
        if [ -n "$stripe_price_annual" ]; then
            if upsert_env_var "$convex_env_file" "STRIPE_PRICE_ID_PRO_ANNUAL" "$stripe_price_annual"; then
                synced_count=$((synced_count + 1))
            fi
        fi

        # Resend API key
        if [ -n "$resend_api_key" ]; then
            if upsert_env_var "$convex_env_file" "RESEND_API_KEY" "$resend_api_key"; then
                synced_count=$((synced_count + 1))
            fi
        fi
    else
        log_warn "app/.env.convex.local not found, skipping Convex secrets"
    fi

    # NOTE: No shared secrets sync to .env.nextjs.local
    # - Novu credentials are PER-AGENT (from setup-novu-org.sh)
    # - Convex URLs are generated by agent-init.sh

    if [ $synced_count -gt 0 ]; then
        log_success "Synced $synced_count shared secret(s)"
    else
        log_info "No secrets to sync (all up to date or missing in shared file)"
    fi
}

# =============================================================================
# Upsert (update or insert) an environment variable in a file
# =============================================================================
# Usage: upsert_env_var <file> <key> <value>
# Returns 0 if changed, 1 if unchanged
upsert_env_var() {
    local file="$1"
    local key="$2"
    local value="$3"

    if [ ! -f "$file" ]; then
        return 1
    fi

    # Check if key exists (commented or uncommented)
    if grep -q "^${key}=" "$file"; then
        # Key exists - check if value is different
        local current_value=$(grep "^${key}=" "$file" | cut -d= -f2-)
        if [ "$current_value" = "$value" ]; then
            return 1  # No change needed
        fi
        # Update existing value
        local temp_file=$(mktemp)
        sed "s|^${key}=.*|${key}=${value}|" "$file" > "$temp_file"
        mv "$temp_file" "$file"
        return 0
    elif grep -q "^# *${key}=" "$file"; then
        # Key exists but is commented out - uncomment and update
        local temp_file=$(mktemp)
        sed "s|^# *${key}=.*|${key}=${value}|" "$file" > "$temp_file"
        mv "$temp_file" "$file"
        return 0
    else
        # Key doesn't exist - append it
        echo "${key}=${value}" >> "$file"
        return 0
    fi
}

# =============================================================================
# STEP 2: Verify Orchestrator
# =============================================================================
verify_orchestrator() {
    log_step "Step 2: Verify Orchestrator"

    # Check if orchestrator proxy is running
    if curl -sk -o /dev/null -w "%{http_code}" https://novu.loc/ 2>/dev/null | grep -q "200\|302"; then
        log_success "Orchestrator proxy running"
    else
        log_warn "Orchestrator not responding"
        log_info "Starting orchestrator..."

        if [ -d "$ORCHESTRATOR_DIR" ]; then
            cd "$ORCHESTRATOR_DIR"
            ./start.sh
            cd "$PROJECT_ROOT"

            # Wait for it to be ready
            sleep 3

            if curl -sk -o /dev/null https://novu.loc/ 2>/dev/null; then
                log_success "Orchestrator started"
            else
                log_error "Failed to start orchestrator"
                exit 1
            fi
        else
            log_error "Orchestrator not found at $ORCHESTRATOR_DIR"
            log_info "Please start it manually: cd ../artifact-review-orchestrator && ./start.sh"
            exit 1
        fi
    fi

    # Check Novu is accessible
    if curl -sk -o /dev/null -w "%{http_code}" https://api.novu.loc/v1/health 2>/dev/null | grep -q "200"; then
        log_success "Novu API healthy"
    else
        log_warn "Novu API not responding (may need a moment to start)"
    fi
}

# =============================================================================
# STEP 3: Install Dependencies
# =============================================================================
install_dependencies() {
    log_step "Step 3: Install Dependencies"

    cd "$APP_DIR"

    if [ -d "node_modules" ] && [ -f "node_modules/.package-lock.json" ]; then
        log_success "node_modules exists"
        log_info "Run 'npm install' manually if you need to update dependencies"
    else
        log_info "Installing npm dependencies..."
        # Use --legacy-peer-deps to handle peer dependency conflicts
        npm install --legacy-peer-deps
        log_success "Dependencies installed"
    fi

    cd "$PROJECT_ROOT"
}

# =============================================================================
# STEP 4: Start Convex Container
# =============================================================================
start_convex_container() {
    log_step "Step 4: Start Convex Container"

    source "$PROJECT_ROOT/.env.docker.local"

    # Check if Convex container is running
    if docker ps --format '{{.Names}}' | grep -q "^${AGENT_NAME}-backend$"; then
        log_success "Convex container running: ${AGENT_NAME}-backend"
    else
        log_info "Starting Convex container..."
        # The start-dev-servers.sh handles Docker startup
        # But we need to do initial Docker setup first

        cd "$PROJECT_ROOT"

        # Export all env vars from .env.docker.local for docker compose
        set -a
        source "$PROJECT_ROOT/.env.docker.local"
        set +a
        export COMPOSE_PROJECT_NAME="$AGENT_NAME"

        # Use --env-file to override the default .env file
        docker compose --env-file "$PROJECT_ROOT/.env.docker.local" up -d

        log_info "Waiting for Convex to initialize..."
        local max_wait=30
        local waited=0
        local ready=false

        while [ $waited -lt $max_wait ]; do
            # Check if container is running and responsive
            if docker ps --format '{{.Names}}' | grep -q "^${AGENT_NAME}-backend$"; then
                # Try to check if Convex is accepting commands
                if docker exec "${AGENT_NAME}-backend" test -f /root/.convex/initialized 2>/dev/null; then
                    ready=true
                    break
                fi
            fi
            sleep 1
            ((waited++))
        done

        if [ "$ready" = true ]; then
            log_success "Convex container ready after ${waited}s"
        elif docker ps --format '{{.Names}}' | grep -q "^${AGENT_NAME}-backend$"; then
            log_warn "Convex container running but may not be fully initialized (waited ${max_wait}s)"
            log_info "Continuing anyway - setup-convex-env.sh will verify later"
        else
            log_error "Failed to start Convex container"
            exit 1
        fi
    fi

}

# =============================================================================
# STEP 5: Setup Novu Organization
# =============================================================================
setup_novu() {
    log_step "Step 5: Setup Novu Organization"

    source "$PROJECT_ROOT/.env.docker.local"

    cd "$PROJECT_ROOT"

    if [ -x "./scripts/setup-novu-org.sh" ]; then
        log_info "Setting up Novu organization for $AGENT_NAME..."
        ./scripts/setup-novu-org.sh
        log_success "Novu organization configured"
    else
        log_warn "setup-novu-org.sh not found or not executable"
    fi
}

# =============================================================================
# STEP 6: Configure Convex Environment
# =============================================================================
configure_convex_env() {
    log_step "Step 6: Configure Convex Environment"

    # Run setup-convex-env.sh to get admin key and configure
    # This runs AFTER Novu setup so NOVU_* vars are available
    log_info "Configuring Convex environment (including Novu keys)..."
    cd "$PROJECT_ROOT"

    if [ -x "./scripts/setup-convex-env.sh" ]; then
        # Capture output to log file for debugging
        local log_file="/tmp/convex-setup-${AGENT_NAME}.log"

        if ./scripts/setup-convex-env.sh 2>&1 | tee "$log_file"; then
            log_success "Convex environment configured"
        else
            log_error "Convex setup failed. Full log:"
            echo "----------------------------------------"
            cat "$log_file"
            echo "----------------------------------------"
            log_info "Log saved to: $log_file"
            exit 1
        fi
    else
        log_warn "setup-convex-env.sh not found or not executable"
    fi
}

# =============================================================================
# STEP 6.5: Validate Convex Environment
# =============================================================================
validate_convex_env() {
    log_step "Step 6.5: Validate Convex Environment"

    cd "$APP_DIR"

    # Determine which env file to use
    local env_file="$APP_DIR/.env.nextjs.local"
    [ ! -f "$env_file" ] && env_file="$APP_DIR/.env.local"

    if [ ! -f "$env_file" ]; then
        log_error "No .env.nextjs.local or .env.local found"
        exit 1
    fi

    # Critical vars that MUST be set for the app to function
    local critical_vars=(
        "RESEND_API_KEY"
        "EMAIL_FROM_AUTH"
        "STRIPE_SECRET_KEY"
        "JWT_PRIVATE_KEY"
        "INTERNAL_API_KEY"
    )

    local missing=()
    local checked=0

    log_info "Validating critical environment variables..."

    for var in "${critical_vars[@]}"; do
        local value=$(npx convex env get "$var" --env-file "$env_file" 2>/dev/null || echo "")
        if [ -z "$value" ]; then
            missing+=("$var")
            echo -e "  ${RED}❌ $var${NC}: not set in Convex"
        else
            echo -e "  ${GREEN}✅ $var${NC}: set"
            ((checked++))
        fi
    done

    if [ ${#missing[@]} -gt 0 ]; then
        echo ""
        log_error "Critical Convex variables not set: ${missing[*]}"
        log_info ""
        log_info "This usually means setup-convex-env.sh failed to sync variables."
        log_info ""
        log_info "Troubleshooting steps:"
        log_info "  1. Check if .env.convex.local has the missing variables"
        log_info "  2. Try: ./scripts/setup-convex-env.sh --sync"
        log_info "  3. Verify with: ./scripts/setup-convex-env.sh --check"
        log_info "  4. Check Convex logs: docker logs ${AGENT_NAME}-backend --tail 50"
        exit 1
    fi

    log_success "All $checked critical variables validated"
}

# =============================================================================
# STEP 7: Final Status
# =============================================================================
show_status() {
    log_step "Setup Complete"

    source "$PROJECT_ROOT/.env.docker.local"

    echo ""
    echo "Agent: $AGENT_NAME"
    echo ""
    echo "URLs:"
    echo "  App:      https://${AGENT_NAME}.loc"
    echo "  Convex:   https://${AGENT_NAME}.convex.cloud.loc"
    echo "  Mailpit:  https://${AGENT_NAME}.mailpit.loc"
    echo "  Novu:     https://novu.loc"
    echo ""
    echo "Next steps:"
    echo "  1. Start dev servers:  ./scripts/start-dev-servers.sh"
    echo "  2. View app:           https://${AGENT_NAME}.loc"
    echo ""
    echo "Tmux sessions (after starting):"
    echo "  tmux attach -t ${AGENT_NAME}-nextjs"
    echo "  tmux attach -t ${AGENT_NAME}-convex-dev"
    echo ""
}

# =============================================================================
# Check mode
# =============================================================================
check_status() {
    log_step "Checking Agent Status"

    # Detect agent name
    local detected_name=$(detect_agent_name)
    if [ -n "$detected_name" ]; then
        log_success "Detected agent name: $detected_name"
    else
        log_warn "Could not detect agent name from directory"
    fi

    # Check orchestrator config
    if [ -f "$ORCHESTRATOR_CONFIG" ]; then
        local app_port=$(get_agent_config "$detected_name" "appPort")
        local subnet=$(get_agent_config "$detected_name" "subnet")
        if [ -n "$app_port" ] && [ -n "$subnet" ]; then
            log_success "Orchestrator config: appPort=$app_port, subnet=$subnet"
        else
            log_warn "Agent '$detected_name' not found in orchestrator config"
        fi
    else
        log_warn "Orchestrator config not found"
    fi

    if [ -f "$PROJECT_ROOT/.env.docker.local" ]; then
        source "$PROJECT_ROOT/.env.docker.local"
        log_success ".env.docker.local exists (AGENT_NAME=${AGENT_NAME:-NOT SET})"
    else
        log_warn ".env.docker.local not found (run agent-init.sh to generate)"
    fi

    # Check env files
    [ -f "$PROJECT_ROOT/.env.dev.local" ] && log_success ".env.dev.local exists" || log_warn ".env.dev.local missing"
    [ -f "$APP_DIR/.env.nextjs.local" ] && log_success "app/.env.nextjs.local exists" || log_warn "app/.env.nextjs.local missing"
    [ -f "$APP_DIR/.env.convex.local" ] && log_success "app/.env.convex.local exists" || log_warn "app/.env.convex.local missing"

    # Check credential sync status
    check_credential_sync_status

    # Check orchestrator
    if curl -sk -o /dev/null https://novu.loc/ 2>/dev/null; then
        log_success "Orchestrator running"
    else
        log_warn "Orchestrator not running"
    fi

    # Check Docker
    if [ -n "$AGENT_NAME" ] && docker ps --format '{{.Names}}' | grep -q "^${AGENT_NAME}-backend$"; then
        log_success "Convex container running"
    else
        log_warn "Convex container not running"
    fi

    # Check tmux sessions
    if [ -n "$AGENT_NAME" ]; then
        tmux has-session -t "${AGENT_NAME}-nextjs" 2>/dev/null && log_success "tmux: ${AGENT_NAME}-nextjs" || log_warn "tmux: ${AGENT_NAME}-nextjs not running"
        tmux has-session -t "${AGENT_NAME}-convex-dev" 2>/dev/null && log_success "tmux: ${AGENT_NAME}-convex-dev" || log_warn "tmux: ${AGENT_NAME}-convex-dev not running"
    fi
}

# =============================================================================
# Check credential sync status (shared parent → local)
# =============================================================================
check_credential_sync_status() {
    log_step "Credential Sync Status (shared → local)"

    local shared_env_file="$PROJECT_ROOT/../.env.dev.local"
    local convex_env_file="$APP_DIR/.env.convex.local"
    local nextjs_env_file="$APP_DIR/.env.nextjs.local"

    if [ ! -f "$shared_env_file" ]; then
        log_warn "Shared .env.dev.local not found - cannot check sync status"
        return 0
    fi

    local needs_sync=false

    # Helper function to check a single var
    # Usage: check_var_sync "VAR_NAME" "shared_file" "local_file" ["LOCAL_VAR_NAME"]
    check_var_sync() {
        local var_name="$1"
        local shared_file="$2"
        local local_file="$3"
        local local_var_name="${4:-$var_name}"

        local shared_val=$(grep "^${var_name}=" "$shared_file" 2>/dev/null | cut -d= -f2-)
        local local_val=$(grep "^${local_var_name}=" "$local_file" 2>/dev/null | cut -d= -f2-)

        # Truncate for display (show first 12 chars of value)
        local shared_display="${shared_val:0:12}"
        local local_display="${local_val:0:12}"
        [ ${#shared_val} -gt 12 ] && shared_display="${shared_display}..."
        [ ${#local_val} -gt 12 ] && local_display="${local_display}..."

        if [ -z "$shared_val" ]; then
            echo -e "  ${var_name}: ${YELLOW}⚠️  Not in shared${NC}"
        elif [ ! -f "$local_file" ]; then
            echo -e "  ${var_name}: ${RED}❌ Local file missing${NC}"
            needs_sync=true
        elif [ -z "$local_val" ]; then
            echo -e "  ${var_name}: ${RED}❌ Missing in local${NC}"
            needs_sync=true
        elif [ "$shared_val" = "$local_val" ]; then
            echo -e "  ${var_name}: ${GREEN}✅ In sync${NC}"
        else
            echo -e "  ${var_name}: ${RED}❌ Out of sync${NC} (shared: ${shared_display}, local: ${local_display})"
            needs_sync=true
        fi
    }

    echo ""
    echo "Convex secrets (app/.env.convex.local):"
    check_var_sync "STRIPE_SECRET_KEY" "$shared_env_file" "$convex_env_file"
    check_var_sync "STRIPE_WEBHOOK_SECRET" "$shared_env_file" "$convex_env_file"
    check_var_sync "STRIPE_PRICE_ID_PRO" "$shared_env_file" "$convex_env_file"
    check_var_sync "STRIPE_PRICE_ID_PRO_ANNUAL" "$shared_env_file" "$convex_env_file"
    check_var_sync "RESEND_API_KEY" "$shared_env_file" "$convex_env_file"

    echo ""
    echo "Next.js secrets (app/.env.nextjs.local):"
    check_var_sync "NOVU_SECRET_KEY" "$shared_env_file" "$nextjs_env_file"
    check_var_sync "NOVU_APPLICATION_IDENTIFIER" "$shared_env_file" "$nextjs_env_file" "NEXT_PUBLIC_NOVU_APPLICATION_IDENTIFIER"

    echo ""
    if [ "$needs_sync" = true ]; then
        log_warn "Some credentials need syncing"
        echo ""
        echo "Run to synchronize:"
        echo "  ./scripts/agent-init.sh --sync-secrets"
        echo "  ./scripts/setup-convex-env.sh --sync"
    else
        log_success "All credentials in sync"
    fi
}

# =============================================================================
# Sync secrets only (non-disruptive mode)
# =============================================================================
sync_secrets_only() {
    log_step "Syncing Shared Secrets"

    # Detect agent name
    AGENT_NAME=$(detect_agent_name)
    if [ -z "$AGENT_NAME" ]; then
        log_error "Could not detect agent name from directory"
        exit 1
    fi

    log_success "Detected agent name: $AGENT_NAME"

    # Run the sync
    sync_shared_secrets

    echo ""
    log_info "To push these changes to Convex, run:"
    echo "  ./scripts/setup-convex-env.sh --sync"
}

# =============================================================================
# Main
# =============================================================================
main() {
    echo ""
    echo "╔════════════════════════════════════════════════════════════╗"
    echo "║          Agent First-Time Initialization                  ║"
    echo "╚════════════════════════════════════════════════════════════╝"
    echo ""

    cd "$PROJECT_ROOT"

    case "${1:-}" in
        --check)
            check_status
            ;;
        --env-only)
            setup_env_files
            log_success "Environment files ready. Run without --env-only for full setup."
            ;;
        --sync-secrets)
            sync_secrets_only
            ;;
        *)
            check_prerequisites
            setup_env_files
            verify_orchestrator
            install_dependencies
            start_convex_container
            setup_novu
            configure_convex_env
            validate_convex_env
            show_status
            ;;
    esac
}

main "$@"
